routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'server', 'as' => 'server.'], function(){
    Route::post('login', 'ServerController@login')->name('doLogin');
    Route::get('login', 'ServerController@showLoginForm')->name('login');
    Route::get('logout', 'ServerController@logout')->name('logout');

    Route::match(['get', 'post'], '/', 'ServerController@index')->name('index');
});

Route::group(['namespace' => 'Gate', 'prefix' => 'gate', 'as' => 'gate.'/* , 'middleware' => 'auth.sso' */], function () {
    Route::get('/', 'GateController@index')->name('dashboard');
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::delete('/{user}', 'UserController@destroy')->name('destroy');
        Route::match(['PUT', 'PATCH'], '/{user}', 'UserController@update')->name('update');
        Route::get('/{user}', 'UserController@show')->name('show');
        Route::post('/', 'UserController@store')->name('store');
        Route::get('/', 'UserController@index')->name('index');
    });
});

// Auth::routes();
// // Authentication Routes...
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// // Password Reset Routes...
// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';

    protected $primaryKey = 'id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_type_id', 'name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    const PAGINATION_LIMIT = 15;

    const USER_STATUS = [
        'active' => 1,
        'inactive' => 0,
    ];

    public function getUserStatusDisplayAttribute()
    {
        return array_flip(self::USER_STATUS)[$this->attributes['status']];
    }

    public function scopeOnlyType($query, $types)
    {
        $_types = !is_array($types) ? [$types] : $types;
        $query->whereIn('users.user_type_id', $_types);
        return $query;
    }

    public function scopeWhereLikes($query, $keyword)
    {
        $query->where(function($q) use($keyword){
            $q->where('users.name', 'like', "%{$keyword}%")
                ->orWhere('users.email', 'like', "%{$keyword}%");
        });
        return $query;
    }

    public function checkPassword($password)
    {
        return Hash::check($password, $this->password);
    }

    public function type()
    {
        return $this->belongsTo(UserType::class, 'user_type_id', 'id');
    }
}

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    protected $table = 'user_types';

    protected $primaryKey = 'id';

    protected $fillable = [
        'id', 'type',
    ];

    public $timestamps = false;

    const USER_TYPES = [
        'admin' => 1,
        'sales' => 2,
        'cs' => 3,
    ];

    public function users()
    {
        return $this->hasMany(User::class, 'user_type_id', 'id');
    }

    public function getLabelTypeDisplayAttribute()
    {
        switch ($this->attributes['id']) {
            case static::USER_TYPES['admin']:
                $label = 'info';
                break;
            case static::USER_TYPES['sales']:
                $label = 'primary';
                break;
            default:
                $label = 'warning';
                break;
        }
        return $label;
    }
}

app/Http/Controllers/Gate/UserController.php
<?php

namespace App\Http\Controllers\Gate;

use App\Models\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequestHandle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::where('users.id', '<>', 1)->with(['type'])->latest();

        $offset = (int) $request->input('page', 1);
        $offset = $offset > 1 ? ($offset - 1) * 15 : 0;

        $users->when(
            $request->has('type') || $request->has('status') || $request->has('keyword'),
            function($query) use($request){
                if ($request->filled('type')) {
                    $query->onlyType($request->type);
                }
                if ($request->filled('status')) {
                    $query->where('users.status', $request->status);
                }
                if ($request->filled('keyword')) {
                    $query->whereLikes($request->keyword);
                }
                return $query;
            }
        );

        $params = $request->only(['type', 'status', 'keyword']);

        $data['offset'] = $offset + 1;
        $data['params'] = $params;
        $data['users'] = $users->paginate()->appends($params);

        $data['title'] = trans('layout.menu.user.title');
        // return $data;
        return view('gate.pages.user.index', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequestHandle $request)
    {
        $messages = [];

        $registered = DB::transaction(function () use($request) {
            $user = User::create([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => bcrypt($request->input('password')),
                'user_type_id' => $request->input('user_type_id'),
                'status' => $request->input('status'),
            ]);
            return $user;
        });

        if ($registered) {
            $messages['success'][] = trans('messages.success.user.created', ['name' => $registered->name]);
            // send email ?
        }else{
            $messages['errors'][] = trans('messages.errors.user.failed_create');
        }
        $request->session()->flash('flash_messages', $messages);
        
        return $registered 
            ? redirect()->route('gate.user.index') 
            : redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::with('type')->find($id);

        $title = trans_choice('page/user.section.detail', !empty($user), [
            'user' => $user ? $user->name : null,
        ]);
        return view('gate.pages.user.detail', compact('user', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param   \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequestHandle $request, $id)
    {
        $user =  User::with('type')->find($id);
        if (!empty($user)) {
            $messages = [];

            $updated = DB::transaction(function () use ($user, $request) {
                $user->name = $request->input('name');
                $user->email = $request->input('email');
                $user->user_type_id = $request->input('user_type_id');
                $user->status = $request->input('status');

                if ($request->filled('password')) {
                    $user->password = bcrypt($request->input('password'));
                }
                return $user->save();
            });

            if ($updated) {
                $messages['success'][] = trans('messages.success.user.updated', ['name' => $user->name]);
            } else {
                $messages['errors'][] = trans('messages.errors.user.failed_update');
            }
            $request->session()->flash('flash_messages', $messages);

            return $updated
                ? redirect()->route('gate.user.show', ['id' => $user->id])
                : redirect()->back()->withInput();
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
            return redirect()->route('gate.user.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $user = User::with('type')->find($id);
        if (!empty($user)) {
            // todo check jika user menghapus dirinya sendiri dan tidak bisa menghapus tipe system admin ?
            $deleted = DB::transaction(function () use ($user) {
                return $user->delete();
            });

            $messages = [];
            if ($deleted) {
                $request->session()->flash('flash_messages', [
                    'success' => trans('messages.success.user.deleted', ['name' => $user->name]),
                ]);
            } else {
                $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.failed_delete')]);
            }
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
        }
        return redirect()->route('gate.user.index');
    }
}

resources/views/gate/pages/user/detail.blade.php
@extends('gate.layouts.app')
@section('content')
    @includeWhen(session('flash_messages'), 'gate.layouts.feedback')
    @if (!empty($user))
        <div class="row">
            <div class="col-md-10 col-xs-offset-1">
                <div class="panel">
                    <div class="panel-heading">
                        <span class="panel-title">
                            {{ trans_choice('page/user.section.detail', 1, ['user' => $user->name]) }}
                        </span>
                    </div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label for="input-name" class="col-sm-2 control-label">@lang('page/user.field.name')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">{{ $user->name }}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="input-email" class="col-sm-2 control-label">@lang('page/user.field.email')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">{{ $user->email }}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="input-user_type" class="col-sm-2 control-label">@lang('page/user.field.user_type')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">
                                        <span class="label label-{{ $user->type->label_type_display }}">{{ $user->type->type }}</span>
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="input-status" class="col-sm-2 control-label">@lang('page/user.field.status.title')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">
                                        <span class="label label-{{ $user->status ? 'success' : 'danger' }}">{{ trans('page/user.field.status.' . $user->user_status_display) }}</span>
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="input-created" class="col-sm-2 control-label">@lang('page/user.field.created_at')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">{{ $user->created_at ? $user->created_at->format('H:i - d F Y') : '-' }}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="input-updated" class="col-sm-2 control-label">@lang('page/user.field.updated_at')</label>
                                <div class="col-sm-8">
                                    <p class="form-control-static">{{ $user->updated_at ? $user->updated_at->format('H:i - d F Y') : '-' }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <a href="{{ url()->previous() != url()->current() ? url()->previous() : route('gate.user.index') }}" class="btn btn-default">@lang('common.buttons.back')</a>
                        <button class="btn btn-success pull-right" data-toggle="modal" data-target="#user-modal"><i class="fa fa-pencil-square-o"></i> @lang('page/user.section.edit')</button>
                    </div>
                </div>
            </div>
        </div>
    @else
        @include('gate.pages.notfound', [
            'route' => route('gate.user.index'),
            'item' => trans('page/user.title')
        ])
    @endif
@endsection
@push('html')
    @includeWhen($user, 'gate.pages.user.modal_user_form', [
        'route' => ['gate.user.update', $user ? $user->id : null],
        'method' => 'PATCH',
        'modalTitle' => trans('page/user.section.edit'),
        'userdata' => $user,
    ])
@endpush

resources/views/gate/pages/user/index.blade.php
@extends('gate.layouts.app')
@section('content')
    @includeWhen(session('flash_messages'), 'gate.layouts.feedback')
    @component('gate.layouts.page_header')
        @slot('title') {{ $title }} @endslot
        <div class="pull-right">
            <button class="btn btn-primary" data-toggle="modal" data-target="#user-modal">
                <i class="fa fa-plus"></i> @lang('page/user.section.add')
            </button>
        </div>
    @endcomponent
    <div class="panel-group" id="filter-group">
        <div class="panel">
            <div class="panel-heading">
                <a class="accordion-toggle {{ !empty($params) ? 'collapsed' : 'collapse' }}" data-toggle="collapse" href="#collapseFilter" data-parent="#filter-group">@lang('page/user.section.filter')</a>
            </div>
            <div id="collapseFilter" class="panel-collapse collapse {{ !empty($params) ? 'in' : '' }}">
                <div class="panel-body">
                    {{ Form::open(['route' => 'gate.user.index', 'method' => 'GET']) }}
                        <div class="row">
                            <div class="form-group col-md-3">
                                <label for="filter-type" class="control-label">@lang('page/user.field.user_type')</label>
                                {{ Form::select('type', $user_types, $params['type'] ?? null, [
                                    'placeholder' => trans('page/user.field.user_type'),
                                    'class' => 'form-control select2',
                                    'id' => 'filter-type'
                                ]) }}
                            </div>
                            <div class="form-group col-md-3">
                                <label for="filter-status" class="control-label">@lang('page/user.field.status.title')</label>
                                {{ Form::select('status', $user_status, $params['status'] ?? null, [
                                    'placeholder' => trans('page/user.field.status.title'),
                                    'class' => 'form-control select2',
                                    'id' => 'filter-status'
                                ]) }}
                            </div>
                            <div class="form-group col-md-4">
                                <label for="filter-keyword" class="control-label">@lang('common.field.keyword')</label>
                                <input type="text" name="keyword" id="filter-keyword" class="form-control" value="{{ $params['keyword'] ?? null }}" placeholder="{{ trans('common.field.keyword') }}" autocomplete="off">
                            </div>
                            <div class="form-group col-md-2">
                                <button type="submit" class="btn btn-primary col-md-12" style="margin-top: 22px;">{{ trans_choice('common.buttons.search', 0) }}</button>
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <span class="panel-title">@lang('layout.menu.user.description')</span>
        </div>
        <div class="panel-body with-margins">
            <div class="table-primary table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 10px;">#</th>
                            <th>@lang('page/user.field.name')</th>
                            <th>@lang('page/user.field.email')</th>
                            <th style="width: 140px;">@lang('page/user.field.user_type')</th>
                            <th style="width: 100px;">@lang('page/user.field.status.title')</th>
                            <th style="width: 160px;">@lang('page/user.field.created_at')</th>
                            <th style="width: 100px;">@lang('common.text.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $user)
                            <tr>
                                <td>{{ $offset++ }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td class="text-left">
                                    <span class="label label-{{ $user->type->label_type_display }}">{{ $user->type->type }}</span>
                                </td>
                                <td class="text-center">
                                    <span class="label label-{{ $user->status ? 'success' : 'danger' }}">{{ trans('page/user.field.status.' . $user->user_status_display) }}</span>
                                </td>
                                <td>{{ $user->created_at ? $user->created_at->format('H:i - d F Y') : '-' }}</td>
                                <td>
                                    <a href="{{ route('gate.user.show', ['user' => $user->id]) }}" class="btn btn-primary" data-toggle="tooltip" title="{{ trans_choice('common.buttons.detail', 0) }}" data-placement="top">
                                        <i class="fa fa-search"></i>
                                    </a>
                                    {{-- <a href="{{ route('gate.user.edit', ['user' => $user->id]) }}" class="btn btn-success" data-toggle="tooltip" title="{{ trans_choice('common.buttons.edit', 0) }}" data-placement="top">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a> --}}
                                    {{ Form::open([
                                        'method'=>'delete',
                                        'route' => ['gate.user.destroy', $user->id],
                                        'style' => 'display:inline;'
                                    ]) }}
                                        <button type="button" class="btn btn-danger confirm-modal"><i class="fa fa-trash-o" data-toggle="tooltip" title="{{ trans_choice('common.buttons.delete', 0) }}" data-placement="top"></i></button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" align="center">{{ trans('messages.errors.empty_data') }}</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="pull-right">
                {!! $users->links() !!}
            </div>
        </div>
    </div>
@endsection
@push('html')
    @include('gate.pages.user.modal_user_form', [
        'route' => 'gate.user.store',
        'method' => 'POST',
        'modalTitle' => trans('page/user.section.add'),
        'userdata' => false,
    ])
@endpush

resources/views/gate/pages/user/modal_user_form.blade.php
<div id="user-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="modalHeading">{{ $modalTitle }}</h4>
            </div>
            {{ Form::open(['route' => $route, 'method' => $method, 'class' => 'form-horizontal']) }}
                <div class="modal-body">
                    <div class="form-group {{ $errors->has('name') ? 'has-error simple' : '' }}" data-id="input-name">
                        <label for="input-name" class="col-sm-2 control-label">@lang('page/user.field.name')</label>
                        <div class="col-sm-8">
                            <input type="text" name="name" value="{{ old('name', $userdata ? $userdata->name : null) }}" class="form-control" id="input-name" placeholder="@lang('page/user.field.name')">
                            {!! $errors->has("name") ? '<p class="help-block" data-id="input-name">'.$errors->first('name').'</p>' : "" !!}
                        </div>
                    </div>
                    <div class="form-group {{ $errors->has('email') ? 'has-error simple' : '' }}" data-id="input-email">
                        <label for="input-email" class="col-sm-2 control-label">@lang('page/user.field.email')</label>
                        <div class="col-sm-8">
                            <input type="email" name="email" value="{{ old('email', $userdata ? $userdata->email : null) }}" class="form-control" id="input-email" placeholder="@lang('page/user.field.email')">
                            {!! $errors->has("email") ? '<p class="help-block" data-id="input-email">'.$errors->first('email').'</p>' : "" !!}
                        </div>
                    </div>
                    <div class="form-group {{ $errors->has('password') ? 'has-error simple' : '' }}" data-id="input-password">
                        <label for="input-password" class="col-sm-2 control-label">@lang('page/user.field.password')</label>
                        <div class="col-sm-8">
                            <input type="password" name="password" class="form-control" id="input-password" placeholder="@lang($userdata ? 'page/user.text.empty_if_not_update' : 'page/user.field.password')">
                            {!! $errors->has("password") ? '<p class="help-block" data-id="input-password">'.$errors->first('password').'</p>' : "" !!}
                        </div>
                    </div>
                    @if ($userdata)
                        <div class="form-group">
                            <label for="input-password-confirmation" class="col-sm-2 control-label">@lang('page/user.field.password_confirmation')</label>
                            <div class="col-sm-8">
                                <input type="password" name="password_confirmation" class="form-control" id="input-password-confirmation" placeholder="@lang('page/user.field.password_confirmation')">
                            </div>
                        </div>
                    @endif
                    <div class="form-group {{ $errors->has('user_type_id') ? 'has-error simple' : '' }}" data-id="input-type">
                        <label for="input-type" class="col-sm-2 control-label">@lang('page/user.field.user_type')</label>
                        <div class="col-sm-8">
                            {{ Form::select('user_type_id', $user_types, old('user_type_id', $userdata ? $userdata->user_type_id : null), [
                                'placeholder' => trans('page/user.field.user_type'),
                                'class' => 'form-control select2', 'id' => 'input-type'
                            ]) }}
                            {!! $errors->has("user_type_id") ? '<p class="help-block" data-id="input-type">'.$errors->first('user_type_id').'</p>' : "" !!}
                        </div>
                    </div>
                    <div class="form-group {{ $errors->has('status') ? 'has-error simple' : '' }}" data-id="input-status">
                        <label for="input-status" class="col-sm-2 control-label">@lang('page/user.field.status.title')</label>
                        <div class="col-sm-8">
                            {{ Form::select('status', $user_status, old('status', $userdata ? $userdata->status : null), [
                                'placeholder' => trans('page/user.field.status.title'),
                                'class' => 'form-control select2', 'id' => 'input-status'
                            ]) }}
                            {!! $errors->has("status") ? '<p class="help-block" data-id="input-status">'.$errors->first('status').'</p>' : "" !!}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">{{ trans_choice('common.buttons.cancel', 0) }}</button>
                    <button type="submit" class="btn btn-primary">@lang('common.buttons.submit')</button>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@if (count($errors) > 0)
    @push('scripts')
        <script type="text/javascript">
            window.initPixel.push(function () {
                $('#user-modal').modal('show'); 
            });
        </script>
    @endpush 
@endif