routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'server', 'as' => 'server.'], function(){
    Route::post('login', 'ServerController@login')->name('doLogin');
    Route::get('login', 'ServerController@showLoginForm')->name('login');
    Route::get('logout', 'ServerController@logout')->name('logout');

    Route::match(['get', 'post'], '/', 'ServerController@index')->name('index');
});

Route::group(['namespace' => 'Gate', 'prefix' => 'gate', 'as' => 'gate.'/* , 'middleware' => 'auth.sso' */], function () {
    Route::get('/', 'GateController@index')->name('dashboard');
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::delete('/{user}', 'UserController@destroy')->name('destroy');
        Route::match(['PUT', 'PATCH'], '/{user}', 'UserController@update')->name('update');
        Route::get('/{user}', 'UserController@show')->name('show');
        Route::post('/', 'UserController@store')->name('store');
        Route::get('/', 'UserController@index')->name('index');
    });
});

// Auth::routes();
// // Authentication Routes...
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// // Password Reset Routes...
// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Gate/GateController.php
<?php

namespace App\Http\Controllers\Gate;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Broker;

class GateController extends Controller
{
    public function index(Request $request)
    {
        $brokers = Broker::active()->where('share_id', '<>', config('bkm.broker_id'))->get();

        $title = trans('layout.menu.dashboard.title');
        return view('gate.pages.dashboard', compact('brokers', 'title'));
    }
}

app/Http/Controllers/Gate/UserController.php
<?php

namespace App\Http\Controllers\Gate;

use App\Models\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequestHandle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::where('users.id', '<>', 1)->with(['type'])->latest();

        $offset = (int) $request->input('page', 1);
        $offset = $offset > 1 ? ($offset - 1) * 15 : 0;

        $users->when(
            $request->has('type') || $request->has('status') || $request->has('keyword'),
            function($query) use($request){
                if ($request->filled('type')) {
                    $query->onlyType($request->type);
                }
                if ($request->filled('status')) {
                    $query->where('users.status', $request->status);
                }
                if ($request->filled('keyword')) {
                    $query->whereLikes($request->keyword);
                }
                return $query;
            }
        );

        $params = $request->only(['type', 'status', 'keyword']);

        $data['offset'] = $offset + 1;
        $data['params'] = $params;
        $data['users'] = $users->paginate()->appends($params);

        $data['title'] = trans('layout.menu.user.title');
        // return $data;
        return view('gate.pages.user.index', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequestHandle $request)
    {
        $messages = [];

        $registered = DB::transaction(function () use($request) {
            $user = User::create([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => bcrypt($request->input('password')),
                'user_type_id' => $request->input('user_type_id'),
                'status' => $request->input('status'),
            ]);
            return $user;
        });

        if ($registered) {
            $messages['success'][] = trans('messages.success.user.created', ['name' => $registered->name]);
            // send email ?
        }else{
            $messages['errors'][] = trans('messages.errors.user.failed_create');
        }
        $request->session()->flash('flash_messages', $messages);
        
        return $registered 
            ? redirect()->route('gate.user.index') 
            : redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::with('type')->find($id);

        $title = trans_choice('page/user.section.detail', !empty($user), [
            'user' => $user ? $user->name : null,
        ]);
        return view('gate.pages.user.detail', compact('user', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param   \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequestHandle $request, $id)
    {
        $user =  User::with('type')->find($id);
        if (!empty($user)) {
            $messages = [];

            $updated = DB::transaction(function () use ($user, $request) {
                $user->name = $request->input('name');
                $user->email = $request->input('email');
                $user->user_type_id = $request->input('user_type_id');
                $user->status = $request->input('status');

                if ($request->filled('password')) {
                    $user->password = bcrypt($request->input('password'));
                }
                return $user->save();
            });

            if ($updated) {
                $messages['success'][] = trans('messages.success.user.updated', ['name' => $user->name]);
            } else {
                $messages['errors'][] = trans('messages.errors.user.failed_update');
            }
            $request->session()->flash('flash_messages', $messages);

            return $updated
                ? redirect()->route('gate.user.show', ['id' => $user->id])
                : redirect()->back()->withInput();
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
            return redirect()->route('gate.user.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $user = User::with('type')->find($id);
        if (!empty($user)) {
            // todo check jika user menghapus dirinya sendiri dan tidak bisa menghapus tipe system admin ?
            $deleted = DB::transaction(function () use ($user) {
                return $user->delete();
            });

            $messages = [];
            if ($deleted) {
                $request->session()->flash('flash_messages', [
                    'success' => trans('messages.success.user.deleted', ['name' => $user->name]),
                ]);
            } else {
                $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.failed_delete')]);
            }
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
        }
        return redirect()->route('gate.user.index');
    }
}

resources/views/gate/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="gt-ie8 gt-ie9 not-ie" lang="{{ app()->getLocale() }}">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>{{ trans_choice('layout.meta.title', !empty($title), ['appname' => config('app.name'), 'title' => $title ?? '']) }}</title>
    <!-- Open Sans font from Google CDN -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin"
        rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pixel-admin.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/widgets.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pages.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/themes.min.css') }}">
    <!--[if lt IE 9]>
        <script src="assets/javascripts/ie.min.js"></script>
    <![endif]-->
    @stack('styles')
</head>

<body class="theme-default main-menu-animated {{ Route::getCurrentRoute()->getName() == 'gate.user.show' ? 'page-profile' : '' }}">
    <div id="main-wrapper">
        <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
            @include('gate.layouts.header')
        </div>

        <div id="main-menu" role="navigation">
            @include('gate.layouts.sidebar')
        </div>

        <div id="content-wrapper">
            @yield('content')
        </div>
        @stack('html')
        <div id="main-menu-bg"></div>
    </div>
    <script src="{{ asset('pixel-admin/js/jquery.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/pixel-admin.min.js') }}"></script>
    <script src="{{ asset('js/gate-app.js') }}"></script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    @stack('scripts')
    <script type="text/javascript">
        window.PixelAdmin.start(window.initPixel, {
            main_menu: {
                detect_active: false,
            }
        });
    </script>
</body>
</html>

resources/views/gate/layouts/auth.blade.php
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8" lang="{{ app()->getLocale() }}"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="gt-ie8 gt-ie9 not-ie" lang="{{ app()->getLocale() }}">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ trans_choice('layout.meta.title', !empty($title), ['appname' => config('app.name'), 'title' => $title ?? '']) }}</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pixel-admin.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/pages.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pixel-admin/css/themes.min.css') }}">
    <!--[if lt IE 9]>
        <script src="{{ asset('pixel-admin/css/ie.min.js') }}"></script>
    <![endif]-->
    @stack('styles')
</head>
<body class="theme-frost page-signin-alt">
    <div class="signin-header">
        <a href="" class="logo">
            <div class="demo-logo bg-primary"><img src="" alt="" style="margin-top: -4px;"></div>&nbsp;
            <strong>{{ config('app.name') }}</strong>
        </a>
    </div>

    @yield('content')

    <script src="{{ asset('pixel-admin/js/jquery.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('pixel-admin/js/pixel-admin.min.js') }}"></script>
    @stack('scripts')
</body>
</html>

resources/views/gate/layouts/feedback.blade.php
@if (session('flash_messages'))
    @foreach (session('flash_messages') as $type => $messages)
        @php
            $_messages = !is_array($messages) ? [$messages] : $messages;
        @endphp
        @foreach ($_messages as $message)
            <div class="alert fade in alert-{{ config('site.flash-message.' . $type, 'info') }}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4>{{ trans('messages.' . $type . '.title') }}</h4>
                {!! $message !!}
            </div>
        @endforeach
    @endforeach
@endif

resources/views/gate/layouts/header.blade.php
<button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">@lang('admin/layout.buttons.hide_menu')</span></button>
<div class="navbar-inner">
    <div class="navbar-header">
        <a href="{{ route('gate.dashboard') }}" class="navbar-brand">
            <div><img alt="{{ config('app.name') }}" src="{{ asset('assets/logo.png') }}"></div>
            {{ config('app.name') }}
        </a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>
    </div>
    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
        <div>
            <ul class="nav navbar-nav"></ul>
            <div class="right clearfix">
                <ul class="nav navbar-nav pull-right right-navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                            <img src="assets/demo/avatars/1.jpg" alt="">
                            <span>auth_user</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href=""><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/gate/layouts/page_header.blade.php
<div class="page-header">
    <h1>{{ $title }}</h1>
    {{ $slot }}
</div>

resources/views/gate/layouts/sidebar.blade.php
<div id="main-menu-inner">
    <ul class="navigation">
        <li class="{{ empty(Request::segment(2)) ? 'active' : '' }}">
            <a href="{{ route('gate.dashboard') }}">
                <i class="menu-icon fa fa-dashboard"></i>
                <span class="mm-text">@lang('layout.menu.dashboard.title')</span>
            </a>
        </li>
         <li class="{{ (Request::segment(2) == 'user') ? 'active' : '' }}">
            <a href="{{ route('gate.user.index') }}">
                <i class="menu-icon fa fa-users"></i>
                <span class="mm-text">@lang('layout.menu.user.title')</span>
            </a>
        </li>
    </ul>
</div>