routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'server', 'as' => 'server.'], function(){
    Route::post('login', 'ServerController@login')->name('doLogin');
    Route::get('login', 'ServerController@showLoginForm')->name('login');
    Route::get('logout', 'ServerController@logout')->name('logout');

    Route::match(['get', 'post'], '/', 'ServerController@index')->name('index');
});

Route::group(['namespace' => 'Gate', 'prefix' => 'gate', 'as' => 'gate.'/* , 'middleware' => 'auth.sso' */], function () {
    Route::get('/', 'GateController@index')->name('dashboard');
    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::delete('/{user}', 'UserController@destroy')->name('destroy');
        Route::match(['PUT', 'PATCH'], '/{user}', 'UserController@update')->name('update');
        Route::get('/{user}', 'UserController@show')->name('show');
        Route::post('/', 'UserController@store')->name('store');
        Route::get('/', 'UserController@index')->name('index');
    });
});

// Auth::routes();
// // Authentication Routes...
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// // Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// // Password Reset Routes...
// Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
// Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Gate/GateController.php
<?php

namespace App\Http\Controllers\Gate;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Broker;

class GateController extends Controller
{
    public function index(Request $request)
    {
        $brokers = Broker::active()->where('share_id', '<>', config('bkm.broker_id'))->get();

        $title = trans('layout.menu.dashboard.title');
        return view('gate.pages.dashboard', compact('brokers', 'title'));
    }
}

app/Http/Controllers/Gate/UserController.php
<?php

namespace App\Http\Controllers\Gate;

use App\Models\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequestHandle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::where('users.id', '<>', 1)->with(['type'])->latest();

        $offset = (int) $request->input('page', 1);
        $offset = $offset > 1 ? ($offset - 1) * 15 : 0;

        $users->when(
            $request->has('type') || $request->has('status') || $request->has('keyword'),
            function($query) use($request){
                if ($request->filled('type')) {
                    $query->onlyType($request->type);
                }
                if ($request->filled('status')) {
                    $query->where('users.status', $request->status);
                }
                if ($request->filled('keyword')) {
                    $query->whereLikes($request->keyword);
                }
                return $query;
            }
        );

        $params = $request->only(['type', 'status', 'keyword']);

        $data['offset'] = $offset + 1;
        $data['params'] = $params;
        $data['users'] = $users->paginate()->appends($params);

        $data['title'] = trans('layout.menu.user.title');
        // return $data;
        return view('gate.pages.user.index', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequestHandle $request)
    {
        $messages = [];

        $registered = DB::transaction(function () use($request) {
            $user = User::create([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => bcrypt($request->input('password')),
                'user_type_id' => $request->input('user_type_id'),
                'status' => $request->input('status'),
            ]);
            return $user;
        });

        if ($registered) {
            $messages['success'][] = trans('messages.success.user.created', ['name' => $registered->name]);
            // send email ?
        }else{
            $messages['errors'][] = trans('messages.errors.user.failed_create');
        }
        $request->session()->flash('flash_messages', $messages);
        
        return $registered 
            ? redirect()->route('gate.user.index') 
            : redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param  @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::with('type')->find($id);

        $title = trans_choice('page/user.section.detail', !empty($user), [
            'user' => $user ? $user->name : null,
        ]);
        return view('gate.pages.user.detail', compact('user', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param   \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequestHandle $request, $id)
    {
        $user =  User::with('type')->find($id);
        if (!empty($user)) {
            $messages = [];

            $updated = DB::transaction(function () use ($user, $request) {
                $user->name = $request->input('name');
                $user->email = $request->input('email');
                $user->user_type_id = $request->input('user_type_id');
                $user->status = $request->input('status');

                if ($request->filled('password')) {
                    $user->password = bcrypt($request->input('password'));
                }
                return $user->save();
            });

            if ($updated) {
                $messages['success'][] = trans('messages.success.user.updated', ['name' => $user->name]);
            } else {
                $messages['errors'][] = trans('messages.errors.user.failed_update');
            }
            $request->session()->flash('flash_messages', $messages);

            return $updated
                ? redirect()->route('gate.user.show', ['id' => $user->id])
                : redirect()->back()->withInput();
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
            return redirect()->route('gate.user.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $user = User::with('type')->find($id);
        if (!empty($user)) {
            // todo check jika user menghapus dirinya sendiri dan tidak bisa menghapus tipe system admin ?
            $deleted = DB::transaction(function () use ($user) {
                return $user->delete();
            });

            $messages = [];
            if ($deleted) {
                $request->session()->flash('flash_messages', [
                    'success' => trans('messages.success.user.deleted', ['name' => $user->name]),
                ]);
            } else {
                $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.failed_delete')]);
            }
        }else{
            $request->session()->flash('flash_messages', ['errors' => trans('messages.errors.user.notfound')]);
        }
        return redirect()->route('gate.user.index');
    }
}

resources/views/gate/pages/dashboard.blade.php
@extends('gate.layouts.app')
@section('content')
    @component('gate.layouts.page_header')
        @slot('title') {{ $title }} @endslot
    @endcomponent
    <div class="row">
        @foreach ($brokers as $broker)
            <div class="col-md-6">
                <div class="stat-panel">
                    <div class="stat-cell bg-danger valign-middle">
                        <i class="fa fa-truck bg-icon"></i>
                        <span class="text-xlg"><strong>{{ $broker->name }}</strong></span><br>
                        <span class="text-sm"><a href="{{ $broker->url }}">{{ trans('layout.menu.dashboard.to_app') }}</a></span>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/gate/pages/login.blade.php
@extends('gate.layouts.auth')
@section('content')
    <h1 class="form-header">@lang('layout.menu.login.description')</h1>
    {!! Form::open([
        'url' => route('server.login', $params),
        'method'=>'post',
        'id'=>'signin-form',
        'class'=>'panel'
    ]) !!}
        @includeWhen(session('flash_messages'), 'gate.layouts.feedback')
        <div class="form-group {{ $errors->has('email') ? 'has-error simple' : '' }}">
            <input type="text" name="email" id="input-email" class="form-control input-lg" placeholder="{{ trans('page/user.field.email') }}" value="{{ old('email') }}">
            {!! $errors->has("email") ? '<p class="help-block" data-id="input-email">'.$errors->first('email').'</p>' : "" !!}
        </div>
        <div class="form-group {{ $errors->has('password') ? 'has-error simple' : '' }}">
            <input type="password" name="password" id="input-password" class="form-control input-lg" value="" placeholder="{{ trans('page/user.field.password') }}">
            {!! $errors->has("password") ? '<p class="help-block" data-id="input-password">'.$errors->first('password').'</p>' : "" !!}
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary btn-block btn-lg">@lang('common.buttons.sign_in')</button>
        </div>
    {!! Form::close() !!}
@endsection

resources/views/gate/pages/notfound.blade.php
<div class="row">
    <div class="col-md-12">        
        <div class="panel no-border panel-dark">
            <div class="panel-body text-center">
                <h3 class="text-lg text-slim text-warning">
                    <i class="fa fa-warning text-yellow"></i>
                    {{ trans_choice('messages.errors.not_found', !empty($item), ['item' => $item ?? '']) }}
                </h3>
                <p style="margin: 20px 0 20px 0;">
                    {!! trans('layout.notfound.back_or_search', [
                        'url' => url()->previous() != url()->current() ? url()->previous() : $route,
                    ]) !!}
                </p>
                {{ Form::open([
                    'url' => $route,
                    'method' => "GET",
                    'class' => 'form-inline',
                ]) }}
                    <div class="form-group">
                        <label class="sr-only" for="input-keyword">@lang('common.field.keyword')</label>
                        <input type="text" name="keyword" class="form-control" id="input-keyword" placeholder="@lang('common.field.keyword')">
                    </div>
                    <button type="submit" class="btn btn-primary">{{ trans_choice('common.buttons.search', !empty($item), ['item' => $item ?? '']) }}</button>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>